version: "3"

services: 
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
        volumes: 
            - /home/vinibeloni/mongodb/data:/data/db
        networks: 
            - db-networks

networks: 
    db-networks:
        driver: bridge